## Config file
lr:              1e-4 # Initial learning rate
weight_decay:    1e-5
power:           0.9
epochs:          100 # Number of epochs to train the model   
number_classes:  4 # Number of classes in the target dataset
batch_size_tr:   1 # Batch size for train
batch_size_va:   1 # Batch size for validationn 
modalities:      ['flair', 't1', 't1ce', 't2'] # fets: ['flair', 't1', 't1ce', 't2'] brats: ['t2f', 't1n', 't1c', 't2w']
path_to_data:    '/data/birth/cyf/shared_data/FeTS2024' # path to dataset
path_to_log:     '/data/birth/cyf/output/zsh_output/log' # path to save results
progress_p:      0.1 # value between 0-1 shows the number of time we need to report training progress in each epoch
validation_p:    0.1 # validation percentage
test_p:          0.2 # Test percentage (20%)
inputshape:      [160, 192, 128]
weight_mispath:  0.6
weight_content:  0.2
dataset:         'fets'
